Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def rref(A):    
    
    # Loop through rows of A
    nrows, ncols = A.shape
    col = 0
    for row in range(nrows):
        
        # Swap current row if pivot element is zero
        pivotrow = row
        while A[pivotrow,col] == 0:
            pivotrow += 1
            if pivotrow == nrows:
                pivotrow, col = row, col + 1
                if col == ncols:
                    break
        
        A[row,:], A[pivotrow,:] = A[pivotrow,:], A[row,:]
        
        # Perform partial pivoting (swap pivot row if there is a larger value in the pivot column)
        for i in range(row + 1, nrows):
            if abs(A[i,col]) > abs(A[row,col]):
                A[row,:], A[i,:] = A[i,:], A[row,:]
        
        # Row reduce non-pivot rows
        display(A)
        for i in range(nrows):
            if i != row and A[row,col] != 0:
                A[i,:] -= A[i,col] / A[row,col] * A[row,:]
                
        # Divide pivot row by pivot
        A[row,:] /= A[row,col]
        
        # Move to next column
        col += 1
                       
    return A


import sympy as sym

A = sym.Matrix([[1, 0, 2, 0, -1], 
                [2, 0, 4, -2, 4], 
                [0, 1, 1, 2, 0]])
display(A)
display(rref(A))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 39[0m
[1;32m     34[0m         col [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m     36[0m     [38;5;28;01mreturn[39;00m A
[0;32m---> 39[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m [38;5;28;01mas[39;00m [38;5;21;01msym[39;00m
[1;32m     41[0m A [38;5;241m=[39m sym[38;5;241m.[39mMatrix([[[38;5;241m1[39m, [38;5;241m0[39m, [38;5;241m2[39m, [38;5;241m0[39m, [38;5;241m-[39m[38;5;241m1[39m], 
[1;32m     42[0m                 [[38;5;241m2[39m, [38;5;241m0[39m, [38;5;241m4[39m, [38;5;241m-[39m[38;5;241m2[39m, [38;5;241m4[39m], 
[1;32m     43[0m                 [[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m0[39m]])
[1;32m     44[0m display(A)

[0;31mModuleNotFoundError[0m: No module named 'sympy'
ModuleNotFoundError: No module named 'sympy'

